server:
  port: 8080

spring:
  application:
    name: desafioAWS

  cloud:
    aws:
      credentials:
        access-key: x
        secret-key: x
      region:
        static: ${REGION_AWS:us-east-2}
      endpoint: x

      sqs:
        queue-name: sensidia-metadata

