server:
  port: 8080

spring:
  application:
    name: desafioAWS

  cloud:
    aws:
      credentials:
        access-key: x
        secret-key: x
      region:
        static: x
      endpoint: x

      sqs:
        queue-name: sensidia-metadata
      s3:
        bucket-name: upload-sensidia

